# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvnorm <- function(mean, Precision) {
    .Call(`_skewBART_rmvnorm`, mean, Precision)
}

rlgam <- function(shape) {
    .Call(`_skewBART_rlgam`, shape)
}

update_b <- function(Z, b_new, mu_new, b_old, mu_old, cluster_idx, sigma) {
    .Call(`_skewBART_update_b`, Z, b_new, mu_new, b_old, mu_old, cluster_idx, sigma)
}

update_z_multi_2 <- function(Y, mu, Sigma, Z_0) {
    .Call(`_skewBART_update_z_multi_2`, Y, mu, Sigma, Z_0)
}

